// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/evt/secret-home-task/internal/app/domain"

	mock "github.com/stretchr/testify/mock"
)

// BookService is an autogenerated mock type for the BookService type
type BookService struct {
	mock.Mock
}

type BookService_Expecter struct {
	mock *mock.Mock
}

func (_m *BookService) EXPECT() *BookService_Expecter {
	return &BookService_Expecter{mock: &_m.Mock}
}

// CreateBook provides a mock function with given fields: ctx, book
func (_m *BookService) CreateBook(ctx context.Context, book domain.Book) (domain.Book, error) {
	ret := _m.Called(ctx, book)

	if len(ret) == 0 {
		panic("no return value specified for CreateBook")
	}

	var r0 domain.Book
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Book) (domain.Book, error)); ok {
		return rf(ctx, book)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Book) domain.Book); ok {
		r0 = rf(ctx, book)
	} else {
		r0 = ret.Get(0).(domain.Book)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Book) error); ok {
		r1 = rf(ctx, book)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BookService_CreateBook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBook'
type BookService_CreateBook_Call struct {
	*mock.Call
}

// CreateBook is a helper method to define mock.On call
//   - ctx context.Context
//   - book domain.Book
func (_e *BookService_Expecter) CreateBook(ctx interface{}, book interface{}) *BookService_CreateBook_Call {
	return &BookService_CreateBook_Call{Call: _e.mock.On("CreateBook", ctx, book)}
}

func (_c *BookService_CreateBook_Call) Run(run func(ctx context.Context, book domain.Book)) *BookService_CreateBook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Book))
	})
	return _c
}

func (_c *BookService_CreateBook_Call) Return(_a0 domain.Book, _a1 error) *BookService_CreateBook_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BookService_CreateBook_Call) RunAndReturn(run func(context.Context, domain.Book) (domain.Book, error)) *BookService_CreateBook_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBook provides a mock function with given fields: ctx, id
func (_m *BookService) DeleteBook(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBook")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BookService_DeleteBook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBook'
type BookService_DeleteBook_Call struct {
	*mock.Call
}

// DeleteBook is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *BookService_Expecter) DeleteBook(ctx interface{}, id interface{}) *BookService_DeleteBook_Call {
	return &BookService_DeleteBook_Call{Call: _e.mock.On("DeleteBook", ctx, id)}
}

func (_c *BookService_DeleteBook_Call) Run(run func(ctx context.Context, id int)) *BookService_DeleteBook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *BookService_DeleteBook_Call) Return(_a0 error) *BookService_DeleteBook_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BookService_DeleteBook_Call) RunAndReturn(run func(context.Context, int) error) *BookService_DeleteBook_Call {
	_c.Call.Return(run)
	return _c
}

// GetBook provides a mock function with given fields: ctx, id
func (_m *BookService) GetBook(ctx context.Context, id int) (domain.Book, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetBook")
	}

	var r0 domain.Book
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (domain.Book, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) domain.Book); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Book)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BookService_GetBook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBook'
type BookService_GetBook_Call struct {
	*mock.Call
}

// GetBook is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *BookService_Expecter) GetBook(ctx interface{}, id interface{}) *BookService_GetBook_Call {
	return &BookService_GetBook_Call{Call: _e.mock.On("GetBook", ctx, id)}
}

func (_c *BookService_GetBook_Call) Run(run func(ctx context.Context, id int)) *BookService_GetBook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *BookService_GetBook_Call) Return(_a0 domain.Book, _a1 error) *BookService_GetBook_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BookService_GetBook_Call) RunAndReturn(run func(context.Context, int) (domain.Book, error)) *BookService_GetBook_Call {
	_c.Call.Return(run)
	return _c
}

// GetBooks provides a mock function with given fields: ctx, categoryIDs, limit, offset
func (_m *BookService) GetBooks(ctx context.Context, categoryIDs []int, limit int, offset int) ([]domain.Book, error) {
	ret := _m.Called(ctx, categoryIDs, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetBooks")
	}

	var r0 []domain.Book
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []int, int, int) ([]domain.Book, error)); ok {
		return rf(ctx, categoryIDs, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []int, int, int) []domain.Book); ok {
		r0 = rf(ctx, categoryIDs, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Book)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []int, int, int) error); ok {
		r1 = rf(ctx, categoryIDs, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BookService_GetBooks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBooks'
type BookService_GetBooks_Call struct {
	*mock.Call
}

// GetBooks is a helper method to define mock.On call
//   - ctx context.Context
//   - categoryIDs []int
//   - limit int
//   - offset int
func (_e *BookService_Expecter) GetBooks(ctx interface{}, categoryIDs interface{}, limit interface{}, offset interface{}) *BookService_GetBooks_Call {
	return &BookService_GetBooks_Call{Call: _e.mock.On("GetBooks", ctx, categoryIDs, limit, offset)}
}

func (_c *BookService_GetBooks_Call) Run(run func(ctx context.Context, categoryIDs []int, limit int, offset int)) *BookService_GetBooks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]int), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *BookService_GetBooks_Call) Return(_a0 []domain.Book, _a1 error) *BookService_GetBooks_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BookService_GetBooks_Call) RunAndReturn(run func(context.Context, []int, int, int) ([]domain.Book, error)) *BookService_GetBooks_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBook provides a mock function with given fields: ctx, book
func (_m *BookService) UpdateBook(ctx context.Context, book domain.Book) (domain.Book, error) {
	ret := _m.Called(ctx, book)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBook")
	}

	var r0 domain.Book
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Book) (domain.Book, error)); ok {
		return rf(ctx, book)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Book) domain.Book); ok {
		r0 = rf(ctx, book)
	} else {
		r0 = ret.Get(0).(domain.Book)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Book) error); ok {
		r1 = rf(ctx, book)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BookService_UpdateBook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBook'
type BookService_UpdateBook_Call struct {
	*mock.Call
}

// UpdateBook is a helper method to define mock.On call
//   - ctx context.Context
//   - book domain.Book
func (_e *BookService_Expecter) UpdateBook(ctx interface{}, book interface{}) *BookService_UpdateBook_Call {
	return &BookService_UpdateBook_Call{Call: _e.mock.On("UpdateBook", ctx, book)}
}

func (_c *BookService_UpdateBook_Call) Run(run func(ctx context.Context, book domain.Book)) *BookService_UpdateBook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Book))
	})
	return _c
}

func (_c *BookService_UpdateBook_Call) Return(_a0 domain.Book, _a1 error) *BookService_UpdateBook_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BookService_UpdateBook_Call) RunAndReturn(run func(context.Context, domain.Book) (domain.Book, error)) *BookService_UpdateBook_Call {
	_c.Call.Return(run)
	return _c
}

// NewBookService creates a new instance of BookService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBookService(t interface {
	mock.TestingT
	Cleanup(func())
}) *BookService {
	mock := &BookService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
