with-expecter: true
dir: "mocks"
outpkg: "mocks"
mockname: "{{.InterfaceNameCamel}}"
filename: "{{.InterfaceNameSnake}}_mock.go"
packages:
  github.com/evt/secret-home-task/internal/app/transport/httpserver:
    interfaces:
      BookService:


